name: alphafold3-pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - jax # Necessary so numpy can read bfloat16 parameter files
  - numpy
  - tqdm
  - zstandard
  - gemmi
  - rdkit=2024.03.5
  - modelcif
  - pip:
    - pdbeccdutils